#if !canImport(ObjectiveC)
import XCTest

extension CollectionLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionLoaderTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CollectionLoaderTests.__allTests__CollectionLoaderTests),
    ]
}
#endif
